import { NextFont } from "next/dist/compiled/@next/font";
import { Inter } from "next/font/google";

import "../globals.css";
import Header from "../components/Header";
import Banner from "../components/Banner";

const inter: NextFont = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog Next Js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-7xl mx-auto`}>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );
}
